---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-static
data:
  index.html: |
    <h1 style="color:blue;">Welcome to the sample app!</h1>
    <h2>Chart name: {{ .Chart.Name }}</h2>
    <h2>Chart version: {{ .Chart.Version }}</h2>
    <h2>Release name: {{ .Release.Name }}</h2>
    <h2>Release revision: {{ .Release.Revision }}</h2>
    
    
